CREATE TABLE COMBUSTIVEL
(
  ID INTEGER NOT NULL,
  DESCRICAO VARCHAR(25),
  SIGLA VARCHAR(2),
  PERCENTUALIMPOSTO INTEGER,
  VALOR FLOAT,
  CONSTRAINT PK_COMBUSTIVEL PRIMARY KEY (ID)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON COMBUSTIVEL TO  SYSDBA WITH GRANT OPTION;
 
CREATE TABLE TANQUE
(
  ID INTEGER NOT NULL,
  DESCRICAO VARCHAR(25),
  IDCOMBUSTIVEL INTEGER NOT NULL,
  ARMAZENAMENTO FLOAT,
  CONSTRAINT PK_TANQUE PRIMARY KEY (ID)
);

ALTER TABLE TANQUE ADD CONSTRAINT FK_COMBUSTIVEL
  FOREIGN KEY (IDCOMBUSTIVEL) REFERENCES COMBUSTIVEL (ID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON TANQUE TO  SYSDBA WITH GRANT OPTION;
 
CREATE TABLE BOMBA
(
  ID INTEGER NOT NULL,
  DESCRICAO VARCHAR(25),
  IDTANQUE INTEGER NOT NULL,
  CONSTRAINT PK_BOMBA PRIMARY KEY (ID)
);

ALTER TABLE BOMBA ADD CONSTRAINT FK_TANQUE
  FOREIGN KEY (IDTANQUE) REFERENCES TANQUE (ID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON BOMBA TO  SYSDBA WITH GRANT OPTION;
 
 
CREATE TABLE ABASTECIMENTO
(
  ID INTEGER NOT NULL,
  IDBOMBA INTEGER NOT NULL,
  QUANTIDADE FLOAT,
  VALORUNITARIO FLOAT,
  PERCENTUALIMPOSTO INTEGER,
  VALORIMPOSTO FLOAT,
  VALORTOTAL FLOAT,
  DATAHORA TIMESTAMP,
  CONSTRAINT PK_ABASTECIMENTO PRIMARY KEY (ID)
);

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_BOMBA
  FOREIGN KEY (IDBOMBA) REFERENCES BOMBA (ID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ABASTECIMENTO TO  SYSDBA WITH GRANT OPTION;